package com.skjolberg.nfc.acs;


public enum AcrDefaultLEDAndBuzzerBehaviour {

	PICC_ACTIVATION_STATUS_LED,
	ICC_ACTIVATION_STATUS_LED,
	PICC_POLLING_STATUS_LED,
	CARD_INSERTION_AND_REMOVAL_EVENTS_BUZZER,
	CONTACTLESS_CHIP_RESET_INDICATION_BUZZER,
	EXCLUSIVE_MODE_STATUS_BUZZER,
	LED_CARD_OPERATION_BLINK;

}
